name: Publish package to GitHub Packages
on:
  release:
    types: [ published ]
jobs:
  prepare-deploy:
    name: Upate version ðŸŒ¿
    runs-on: ubuntu-latest
    env:
      ACTION_ACTOR_EMAIL: ${{ secrets.ACTION_ACTOR_EMAIL }}
      TAG_NAME: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Remove snapshot
        run: mvn versions:set -DnewVersion=$TAG_NAME versions:commit
      - name: Commit version
        run: |
          git config --global user.name '$GITHUB_ACTOR'
          git config --global user.email '$ACTION_ACTOR_EMAIL'
          git commit -am "[GitHub action] prepare for release"
          git push

  deploy:
    name: Deploy ðŸš€
    needs: prepare-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post-deploy:
    name: Prepare snapshot ðŸŒ±
    needs: deploy
    runs-on: ubuntu-latest
    env:
      ACTION_ACTOR_EMAIL: ${{ secrets.ACTION_ACTOR_EMAIL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set snapshot version
        run: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit
      - name: Commit snapshot version
        run: |
          git config --global user.name '$GITHUB_ACTOR'
          git config --global user.email '$ACTION_ACTOR_EMAIL'
          git commit -am "[GitHub action] prepare for next development iteration"
          git push